# To revert a specific commit:
# git revert --no-commit <SHA>
# git commit -m "revert: foo bar"
# https://commitizen-tools.github.io/commitizen/faq/#how-to-handle-revert-commits

# To revert a specific bump:
# git tag --delete <created_tag>
# git reset HEAD~
# git reset --hard HEAD
# In case the commit was pushed to the server you can remove it by running:
# git push --delete origin <created_tag>
# https://commitizen-tools.github.io/commitizen/faq/#how-to-revert-a-bump

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "poetry"
update_changelog_on_bump = true
major_version_zero = true
