name: Deploy FTP

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy-ftp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare Content
        run: |
          mkdir content &&
          cp pyproject.toml LICENSE.txt README.md content
      - name: Deploy FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          port: ${{ secrets.FTP_PORT }}
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./content/
          server-dir: ./
          log-level: verbose
