name: Documentation

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Version
        run: |
          echo "PYTHON_VERSION=$(cat ${{ github.workspace }}/pyproject.toml | 
          grep 'python = ' | 
          grep -o -P '(?<=\^).*(?=\")')" >> $GITHUB_ENV
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
      - name: Install
        run: poetry install --only docs
      - name: Deploy Documentation
        run: poetry run mkdocs gh-deploy --force
