name: Documentation

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: ./.github/actions/python
      - name: Install Poetry
        uses: ./.github/actions/poetry
      - name: Install Virtualenv
        uses: ./.github/actions/virtualenv
        with:
          groups: --only docs
      - name: Deploy Documentation
        run: poetry run mkdocs gh-deploy --force
