name: Lint & Test

on:
  pull_request:
  # workflow_run:
  #   workflows: ["Setup"]
  #   types:
  #     - completed

jobs:
  lint-test:
    needs: [Setup]
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Virtualenv
        uses: ./.github/actions/virtualenv
        with:
          groups: --only lint,test
      - name: Lint
        run: poetry run ruff .
      - name: Test
        run: poetry run pytest --cov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          debug: true
          github-token: ${{ github.token }}
