name: Poetry

on:
  workflow_call:

jobs:
  poetry:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - name: Poetry
        if: steps.cache-poetry.outputs.cache-hit != true
        run: curl -sSL https://install.python-poetry.org | python -
