name: Setup

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "**.py"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: ./.github/actions/python
      - name: Install Poetry
        uses: ./.github/actions/poetry
